version: '3.8'  # Specify the version of Docker Compose

services:
  frontend:
    build:
      context: ./frontend  # Path to your frontend directory
      dockerfile: Dockerfile  # Dockerfile name (if it's named Dockerfile, you can omit this line)
    ports:
      - "5173:5173"  # Map port 5173 on the host to port 5173 in the container
    depends_on:
      - backend  # Ensure the backend is started before the frontend

  backend:
    build:
      context: ./backend  # Path to your backend directory
      dockerfile: Dockerfile  # Dockerfile name (if it's named Dockerfile, you can omit this line)
    ports:
      - "5000:5000"  # Map port 5000 on the host to port 5000 in the container